### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by inetman28** [vmware/powerclicore#46]

**Comment by inetman28** [comment]
One more log:
```
PS /root> $error[0] | fl * -Force

writeErrorStream      : True
PSMessageDetails      : 
Exception             : VMware.VimAutomation.Cloud.Types.V1.CIException: 05/01/2020 09:02:04	Connect-CIServer		No Cloud server was found on https://<some_fqdn_of_vcd>:443/api/.	 ---> 
                        VMware.VimAutomation.Cloud.Views.Exceptions.CloudException: No Cloud server was found on https://<some_fqdn_of_vcd>:443/api/. ---> System.Net.Http.HttpRequestException: 
                        An error occurred while sending the request. ---> System.IO.IOException: The 
                        server returned an invalid or unrecognized response.
                           at System.Net.Http.HttpConnection.FillAsync()
                           at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
                           at System.Threading.Tasks.ValueTask`1.get_Result()
                           at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
                           --- End of inner exception stack trace ---
                           at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
                           at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean d
                        oRequestAuth, CancellationToken cancellationToken)
                           at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancel
                        lationToken)
                           at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
                           at VMware.VimAutomation.Cloud.Views.Http.RedirectAuthenticationHandler.SendAsync(HttpRequestMessage request, CancellationToken cance
                        llationToken)
                           at VMware.VimAutomation.Common.Util10.DiagnosticProxyHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationTok
                        en)
                           at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Bool
                        ean disposeCts)
                           at VMware.VimAutomation.Cloud.Views.Http.RestClient.Execute(HttpRequestMessage request)
                           at VMware.VimAutomation.Cloud.Views.Http.RestClient.Execute(Uri uri, HttpMethod method, Object value, IDictionary`2 requestHeaders)
                           at VMware.VimAutomation.Cloud.Views.Http.RestClient.Execute[T](Uri uri, HttpMethod method, IDictionary`2 requestHeaders, Object valu
                        e)
                           at VMware.VimAutomation.Cloud.Views.Http.RestClient.Get[T](Uri uri)
                           at VMware.VimAutomation.Cloud.Views.Http.RestClient.Get[T](String url)
                           at VMware.VimAutomation.Cloud.Views.Connectivity.VersionHelper.GetSupportedVersionsFromServer()
                           at VMware.VimAutomation.Cloud.Views.Connectivity.VersionHelper..ctor(CloudClient client)
                           at VMware.VimAutomation.Cloud.Views.Connectivity.VersionHelper.Negotiate(CloudClient cloudClient)
                           at VMware.VimAutomation.Cloud.Views.CloudClient.EstablishVersionAndLoginUri()
                           at VMware.VimAutomation.Cloud.Views.CloudClient.Connect(String serverUrl, String organization, String username, String password, Fun
                        c`2 clientFactory)
                           --- End of inner exception stack trace ---
                           at VMware.VimAutomation.Cloud.Views.CloudClient.Connect(String serverUrl, String organization, String username, String password, Fun
                        c`2 clientFactory)
                           at VMware.VimAutomation.Cloud.Impl.V1.Service.ConnectivityServiceImpl.ConnectCloudServer(String serverName, String protocol, Int32 p
                        ort, String organization, String username, String password, IServerCertificateValidationHandler certificateValidator)
                           --- End of inner exception stack trace ---
                           at VMware.VimAutomation.Cloud.Impl.V1.Service.ConnectivityServiceImpl.ConnectCloudServer(String serverName, String protocol, Int32 p
                        ort, String organization, String username, String password, IServerCertificateValidationHandler certificateValidator)
                           at VMware.VimAutomation.Cloud.Impl.V1.Service.ClientManagerImpl.ConnectCloudServer(String serverUrl, String protocol, Int32 port, St
                        ring organization, String username, String password, IServerCertificateValidationHandler certificateValidator)
                           at VMware.VimAutomation.Cloud.Commands.Cmdlets.ConnectCIServer.ProcessRecordErrorHandled()
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Connect-CIServer], CIException
FullyQualifiedErrorId : Cloud_ConnectivityServiceImpl_ConnectCloudServer_ConnectError,VMware.VimAutomation.Cloud.Commands.Cmdlets.ConnectCIServer
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

PS /root> 

```

**Comment by inetman28** [comment]
It is not work... This is a bag of powershell... 
`Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Confirm:$false`

After add root ca to container evething work fine.
